"""Static configuration for the Cubicost TME Schematic Table filler.

Everything here is derived from observed TME behaviour (see the plan doc and the
screenshots taken 2026-08-12).  Values that still need to be *measured* rather
than assumed live in ``probe_results.json`` instead -- never guess them here.
"""

from __future__ import annotations

# --------------------------------------------------------------------------
# Schematic Table column layout (left to right, exactly as TME renders it)
# --------------------------------------------------------------------------

# key, TME header text, Excel column letter
COLUMNS: tuple[tuple[str, str, str], ...] = (
    ("name",                  "Name",                  "A"),
    ("circuit_number",        "Circuit Number",        "B"),
    ("cable_spec",            "Cable Specification",   "C"),
    ("terminal_load",         "Terminal Load",         "D"),
    ("corresponding_element", "Corresponding Element", "E"),
    ("conduit_size",          "Conduit Size (mm)",     "F"),
    ("elevation",             "Elevation (m)",         "G"),
    ("system",                "System",                "H"),
    ("remarks",               "Remarks",               "I"),
)

COLUMN_KEYS: tuple[str, ...] = tuple(k for k, _, _ in COLUMNS)
COLUMN_LABELS: dict[str, str] = {k: label for k, label, _ in COLUMNS}
COLUMN_INDEX: dict[str, int] = {k: i for i, (k, _, _) in enumerate(COLUMNS)}
N_COLUMNS = len(COLUMNS)

# Columns the script actually writes into a circuit row.  Order matters: it is
# the left-to-right order we Tab through.
WRITE_KEYS: tuple[str, ...] = (
    "circuit_number",
    "cable_spec",
    "terminal_load",
    "system",
    "remarks",
)

# Columns that are read back to verify a row.  Corresponding Element, Conduit
# Size and Elevation are deliberately excluded: reading a cell requires F2, and
# F2 on the Elevation column makes TME raise "Elevation input error".  Tabbing
# past them is harmless -- only opening their editors is not.
#
# Column alignment is still proven without them.  Name is generated by TME as
# "<board name>-<circuit number>", so if the written values had landed one
# column over, Circuit Number would be empty and Name would show it.
VERIFY_KEYS: tuple[str, ...] = (
    "name",
    "circuit_number",
    "cable_spec",
    "terminal_load",
    "system",
    "remarks",
)

# Columns never to open an editor on, for the reason above.
NEVER_F2_KEYS: frozenset[str] = frozenset(
    {"corresponding_element", "conduit_size", "elevation"}
)

# --------------------------------------------------------------------------
# Excel sentinels
# --------------------------------------------------------------------------

# "use whatever TME already put there" -- do not write, but still verify.
SKIP_TOKEN = "[SKIP]"

# Marks a circuit row: TME generates the Name itself from DB + circuit number.
AUTO_NAME_TOKEN = "[AUTO GENERATED BY ROW B]"

# --------------------------------------------------------------------------
# What TME pre-fills into a freshly created circuit row
# (observed in Screenshot 2026-08-12 205306: row "1.1" after Ctrl+I)
# --------------------------------------------------------------------------

CIRCUIT_DEFAULTS: dict[str, str] = {
    "corresponding_element": "Cable Conduit-Electric Cable",
    "elevation": "Floor_Top_Elevation",
    "system": "Lighting System",
    "circuit_number": "",
    "cable_spec": "",
    "terminal_load": "",
    "conduit_size": "",
    "remarks": "",
}

# TME auto-generates the circuit row's Name from DB name + circuit number.  The
# exact format is unknown until probe P1/P10 measures it, so the full-row sweep
# records this column but does not assert on it.  Column alignment is still
# proven by the other eight positions.
IGNORE_ON_VERIFY: frozenset[str] = frozenset({"name"})

# Default name TME gives a brand-new distribution box row (EPower-1, EPower-2...).
DB_DEFAULT_NAME_PREFIX = "EPower-"

# --------------------------------------------------------------------------
# Business rules
# --------------------------------------------------------------------------

# A circuit whose Cable Specification is exactly this is a spare way.
SPARE_MARKER = "SPARE"

# User decision (2026-08-12): spare rows get the same System as the real ways in
# the same board, so one board never mixes Power System and Lighting System.
# Remarks stays empty for spares.
SPARE_SYSTEM_FALLBACK = "Power System"

# --------------------------------------------------------------------------
# Window / input timing
# --------------------------------------------------------------------------

# The maximised System Diagram dialog.  Focus guard requires this substring in
# the foreground window title before any key is sent.
WINDOW_TITLE_MATCH = "System Diagram"

# How long to wait for focus to come back if the user alt-tabs away mid-run.
FOCUS_REACQUIRE_TIMEOUT_S = 3.0

# Adaptive throttle bounds.  The runtime value is derived from measured latency;
# these are only the hard clamps.  See tmeio.Throttle.
KEY_DELAY_MIN_S = 0.008
KEY_DELAY_MAX_S = 0.200
KEY_DELAY_START_S = 0.015

READ_TIMEOUT_MIN_S = 0.40
READ_TIMEOUT_MAX_S = 2.50
READ_TIMEOUT_START_S = 1.00

# An empty cell answers a Ctrl+C with silence, so a read that expects emptiness
# must not sit through the full timeout -- measured latency is single-digit ms,
# so a fifth of a second is already generous.
EXPECT_EMPTY_TIMEOUT_S = 0.20

# Clipboard poll interval while waiting for TME to answer a Ctrl+C.
CLIPBOARD_POLL_S = 0.015

# win32clipboard can be locked by another app (Excel, Teams...); retry briefly.
CLIPBOARD_OPEN_ATTEMPTS = 12
CLIPBOARD_OPEN_BACKOFF_S = 0.02

# Virtual key code for the abort hotkey (F12).
ABORT_VK = 0x7B
ABORT_KEY_NAME = "F12"

# --------------------------------------------------------------------------
# Files
# --------------------------------------------------------------------------

PROBE_RESULTS_FILE = "probe_results.json"
STATE_FILE = ".state.json"
# Used when no workbook is named on the command line.  Points at the bundled
# example so a fresh clone runs out of the box; real work passes its own path.
DEFAULT_WORKBOOK = "examples/example-schedule.xlsx"

# Where a picture of an unexpected popup is saved when the run stops for one, so
# the user can see what interrupted it rather than just a window title.
INTRUDER_SHOT_FILE = "interrupted_by.png"

# --------------------------------------------------------------------------
# TME's "Save current project?" prompt
# --------------------------------------------------------------------------
#
# TME raises this on its own schedule, mid-run, with Yes as the default button.
# With --auto-dismiss-save the filler answers No and carries on, but only after
# proving the window really is that prompt: its title is compared, and then its
# rendered pixels are matched against a stored reference.  A title alone is not
# enough -- TME reuses the title "OK" for other Yes/No questions, and answering
# an unrecognised one would be a decision this script has no business making.

SAVE_PROMPT_TITLE = "OK"
SAVE_PROMPT_REFERENCE = "save_prompt_reference.png"

# "No" button centre, as a fraction of the prompt's size.
SAVE_PROMPT_NO_RATIO = (0.565, 0.836)

# Mean per-channel pixel difference allowed against the reference (0-255).
# The identical dialog scores 0.00 and a same-size dialog with different wording
# scores about 7, so this sits well clear of both.  Erring low is deliberate:
# failing to recognise the prompt merely stops the run, which is the old
# behaviour, while mistaking another dialog for it means clicking a button in
# something nobody has read.
SAVE_PROMPT_MAX_DIFF = 2.0

# Fractional crop (left, top, right, bottom) compared against the reference.
# Only the message band: the title bar and the button row are excluded because
# they render differently depending on whether the dialog has focus, while the
# wording -- the part that actually identifies the dialog -- does not.
SAVE_PROMPT_COMPARE_BOX = (0.04, 0.24, 0.98, 0.68)
