"""Static configuration for the Cubicost TME Schematic Table filler.

Everything here is derived from observed TME behaviour (see the plan doc and the
screenshots taken 2026-08-12).  Values that still need to be *measured* rather
than assumed live in ``probe_results.json`` instead -- never guess them here.
"""

from __future__ import annotations

# --------------------------------------------------------------------------
# Schematic Table column layout (left to right, exactly as TME renders it)
# --------------------------------------------------------------------------

# key, TME header text, Excel column letter
COLUMNS: tuple[tuple[str, str, str], ...] = (
    ("name",                  "Name",                  "A"),
    ("circuit_number",        "Circuit Number",        "B"),
    ("cable_spec",            "Cable Specification",   "C"),
    ("terminal_load",         "Terminal Load",         "D"),
    ("corresponding_element", "Corresponding Element", "E"),
    ("conduit_size",          "Conduit Size (mm)",     "F"),
    ("elevation",             "Elevation (m)",         "G"),
    ("system",                "System",                "H"),
    ("remarks",               "Remarks",               "I"),
)

COLUMN_KEYS: tuple[str, ...] = tuple(k for k, _, _ in COLUMNS)
COLUMN_LABELS: dict[str, str] = {k: label for k, label, _ in COLUMNS}
COLUMN_INDEX: dict[str, int] = {k: i for i, (k, _, _) in enumerate(COLUMNS)}
N_COLUMNS = len(COLUMNS)

# Columns the script actually writes into a circuit row.  Order matters: it is
# the left-to-right order we Tab through.
WRITE_KEYS: tuple[str, ...] = (
    "circuit_number",
    "cable_spec",
    "terminal_load",
    "system",
    "remarks",
)

# Columns that are read back to verify a row.  Corresponding Element, Conduit
# Size and Elevation are deliberately excluded: reading a cell requires F2, and
# F2 on the Elevation column makes TME raise "Elevation input error".  Tabbing
# past them is harmless -- only opening their editors is not.
#
# Column alignment is still proven without them.  Name is generated by TME as
# "<board name>-<circuit number>", so if the written values had landed one
# column over, Circuit Number would be empty and Name would show it.
VERIFY_KEYS: tuple[str, ...] = (
    "name",
    "circuit_number",
    "cable_spec",
    "terminal_load",
    "system",
    "remarks",
)

# Columns never to open an editor on, for the reason above.
NEVER_F2_KEYS: frozenset[str] = frozenset(
    {"corresponding_element", "conduit_size", "elevation"}
)

# --------------------------------------------------------------------------
# What TME pre-fills into a freshly created circuit row
# (observed in Screenshot 2026-08-12 205306: row "1.1" after Ctrl+I)
# --------------------------------------------------------------------------

CIRCUIT_DEFAULTS: dict[str, str] = {
    "corresponding_element": "Cable Conduit-Electric Cable",
    "elevation": "Floor_Top_Elevation",
    "system": "Lighting System",
    "circuit_number": "",
    "cable_spec": "",
    "terminal_load": "",
    "conduit_size": "",
    "remarks": "",
}

# TME auto-generates the circuit row's Name from DB name + circuit number.  The
# exact format is unknown until probe P1/P10 measures it, so the full-row sweep
# records this column but does not assert on it.  Column alignment is still
# proven by the other eight positions.
IGNORE_ON_VERIFY: frozenset[str] = frozenset({"name"})

# Default name TME gives a brand-new distribution box row (EPower-1, EPower-2...).
DB_DEFAULT_NAME_PREFIX = "EPower-"

# --------------------------------------------------------------------------
# Window / input timing
# --------------------------------------------------------------------------

# The maximised System Diagram dialog.  Focus guard requires this substring in
# the foreground window title before any key is sent.
WINDOW_TITLE_MATCH = "System Diagram"

# How long to wait for focus to come back if the user alt-tabs away mid-run.
FOCUS_REACQUIRE_TIMEOUT_S = 3.0

# Adaptive throttle bounds.  The runtime value is derived from measured latency;
# these are only the hard clamps.  See tmeio.Throttle.
#
# The floor equals the starting delay on purpose: the throttle may only ever slow
# the keys down, never speed them up past the value that has been proven to work.
# Measured 2026-08-19 on EE_Y1_BUILDING with the old 8 ms floor: TME answered in
# 18 ms on average, well under the 50 ms baseline, so the throttle scaled the key
# delay *down* to the clamp -- and at that spacing the grid began dropping
# synthetic keys.  13 read timeouts in 33 seconds over 10 rows followed, an
# editor was left open after one of them (a read that cannot prove an editor is
# open must not send Esc), the write/read sequence slid out of step and a paste
# eventually landed while the clipboard still held a read sentinel, which is how
# "__TMEIO_SENTINEL_000141__" ended up inside a Cable Specification cell.
# The run was also *slower* for it: 3.28 s/row against the 2.4 s/row measured
# when the delay stayed at 15 ms.  Faster keys, less throughput.
#
# Raised again to 30 ms while the table was growing, on the evidence that read
# timeouts tracked key spacing: 1.3 per row at 8 ms, 0.13 at 15 ms, none at
# 30 ms.  That is worth having on its own -- a read that times out leaves a cell
# editor open that nothing is allowed to close -- but note it did **not** fix the
# rows that came out a column out of step.  That was Ctrl+Left landing short
# (see grid.SchematicGrid.home), and it happened just the same at 30 ms.
#
# So this is a floor chosen for quiet reads, not for correctness, and it costs
# real time: about 6.3 s per row against 3.7 s at 15 ms.  Now that the column
# fault is fixed it is worth measuring 15 ms again on a whole building before
# assuming 30 is needed.
KEY_DELAY_MIN_S = 0.030
KEY_DELAY_MAX_S = 0.200
KEY_DELAY_START_S = 0.030

READ_TIMEOUT_MIN_S = 0.40
READ_TIMEOUT_MAX_S = 2.50
READ_TIMEOUT_START_S = 1.00

# An empty cell answers a Ctrl+C with silence, so a read that expects emptiness
# must not sit through the full timeout -- measured latency is single-digit ms,
# so a fifth of a second is already generous.
EXPECT_EMPTY_TIMEOUT_S = 0.20

# Clipboard poll interval while waiting for TME to answer a Ctrl+C.
CLIPBOARD_POLL_S = 0.015

# win32clipboard can be locked by another app (Excel, Teams...); retry briefly.
CLIPBOARD_OPEN_ATTEMPTS = 12
CLIPBOARD_OPEN_BACKOFF_S = 0.02

# Before pasting, wait for the clipboard to go quiet: this many consecutive polls
# with an unchanged clipboard sequence number, or give up after the timeout.
#
# This guards the race the module docstring records: TME can still be finishing
# its own clipboard write when we set ours, and the paste that follows would then
# carry the previously read cell's text.  Checking the content once before
# pasting leaves a gap; waiting for the sequence number to stop moving does not.
#
# Honesty about what this did *not* fix: it was added while chasing rows that
# came out with the Cable Specification holding the previous cell's value, and it
# made no difference -- tracing showed every write had landed in the right cell
# with the right value all along, and the real cause was a Ctrl+Left that
# sometimes stops a column short (see grid.SchematicGrid.home).  It is kept
# because the race it closes is real and was observed before this project's
# rewrite, not because it explains that failure.
CLIPBOARD_SETTLE_SAMPLES = 3
CLIPBOARD_SETTLE_TIMEOUT_S = 1.0

# Virtual key code for the abort hotkey (F12).
ABORT_VK = 0x7B
ABORT_KEY_NAME = "F12"

# --------------------------------------------------------------------------
# TME's "Save current project?" prompt
# --------------------------------------------------------------------------
#
# TME raises this on its own schedule, mid-run, with Yes as the default button.
# With --auto-dismiss-save the filler answers No and carries on, but only after
# proving the window really is that prompt: its title is compared, and then its
# rendered pixels are matched against a stored reference.  A title alone is not
# enough -- TME reuses the title "OK" for other Yes/No questions, and answering
# an unrecognised one would be a decision this script has no business making.

SAVE_PROMPT_TITLE = "OK"

# "No" button centre, as a fraction of the prompt's size.
SAVE_PROMPT_NO_RATIO = (0.565, 0.836)

# Mean per-channel pixel difference allowed against the reference (0-255).
# The identical dialog scores 0.00 and a same-size dialog with different wording
# scores about 7, so this sits well clear of both.  Erring low is deliberate:
# failing to recognise the prompt merely stops the run, which is the old
# behaviour, while mistaking another dialog for it means clicking a button in
# something nobody has read.
SAVE_PROMPT_MAX_DIFF = 2.0

# Fractional crop (left, top, right, bottom) compared against the reference.
# Only the message band: the title bar and the button row are excluded because
# they render differently depending on whether the dialog has focus, while the
# wording -- the part that actually identifies the dialog -- does not.
SAVE_PROMPT_COMPARE_BOX = (0.04, 0.24, 0.98, 0.68)
