"""Conventions of our own Excel schedule format.

Not measured TME behaviour and not client-specific -- these are the sentinels
we chose, and they change only if we change the schedule format.

SPARE_SYSTEM_FALLBACK is the odd one out: it is a rule agreed with a client, so
the value here is only the default.  A client's project.yaml overrides it, and
tme.project.ProjectConfig is what carries the resolved value around.
"""

from __future__ import annotations

# "use whatever TME already put there" -- do not write, but still verify.
SKIP_TOKEN = "[SKIP]"

# Marks a circuit row: TME generates the Name itself from DB + circuit number.
AUTO_NAME_TOKEN = "[AUTO GENERATED BY ROW B]"

# A circuit whose Cable Specification is exactly this is a spare way.
SPARE_MARKER = "SPARE"

# Default only.  Spare ways take the same System as the real ways in the same
# board, so one board never mixes Power System and Lighting System (decided
# 2026-08-12).  Overridden per client in projects/<client>/project.yaml.
SPARE_SYSTEM_FALLBACK = "Power System"
